micronaut:
  server:
    port: 8402
  application:
    name: "auth-service"
  security:
    authentication: bearer
    endpoints:
      login:
        path: /api/auth/login
    token:
      jwt:
        generator:
          access-token:
            expiration: 604800
        signatures:
          secret:
            generator:
              secret: ${JWT_GENERATOR_SIGNATURE_SECRET:}
              jws-algorithm: HS256

eureka:
  client:
    registration:
      enabled: true

mongodb:
  uri: ${MONGO_DB_URI}
netty:
  default:
    allocator:
      max-order: 3
