micronaut:
  application:
    name: authService
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}

mongodb:
  uri: mongodb://${USERNAME}:${PASSWORD}@localhost:27017/${DATABASE_NAME}
netty:
  default:
    allocator:
      max-order: 3
